{
    "openapi":"3.0.0",
    "info":{
        "title": "API - Desafio SOLID Rocketseat",
        "descriptioin": "This is an route project utilized for appling some concepts learned in a course",
        "version": "1.0.0",
        "contact": {
        "email": "bls.dudu@gmail.com"
        }
    },
    "host": "localhost:3333",  
    "version":"1.0.0", 
    "paths": {
        "users":{
            "get": {
                "tags": ["Users"],
                "description": "This method returns the users list from the repository if the id in request.header.user_id is the id of an admin user",
                "summary": "Returns all users in the repository (for admins only)",
                "consumes": "application/json",
                "parameters":{
                    "0": {
                        "name":"user_id",
                        "in": "headers",
                        "description": "ID of the user to turn into an admin",
                        "required": true,
                        "type": "string"
                    }
                },
                "responses": {
                    "200": {
                        "description":"Ok, you are an admin, take the list of users!",
                        "headers": {
                            "user_id": { 
                                "type": "string",
                                "format": "id",
                                "description": "ID of the admin user for permission"    
                            } 
                        },
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "array",
                                    "description": "array of users",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                },
                                "examples": {
                                    "user": {
                                        "value": [{
                                        "id": "Numero gerado automaticamente",
                                        "name" : "Eduardo",
                                        "admin": "true",
                                        "email": "bls.dudu@gmail.com",
                                        "created_at": "2013-03-01T01:10:00",
                                        "updated_at": "2013-03-01T01:10:00"
                                        },
                                        {
                                            "id": "Numero gerado automaticamente",
                                            "name" : "Bruna",
                                            "admin": "false",
                                            "email": "bruna@hotmail.com",
                                            "created_at": "2013-03-01T01:10:00",
                                            "updated_at": "2013-03-01T01:10:00"
                                            },
                                            {
                                                "id": "Numero gerado automaticamente",
                                                "name" : "Matheus",
                                                "admin": "false",
                                                "email": "matheus@gmail.com",
                                                "created_at": "2013-03-01T01:10:00",
                                                "updated_at": "2013-03-01T01:10:00"
                                                }]
                                    }
                                    
                                }
                            }
                        }                     
                    },
                    "400": {
                        "description": "Invalid user or id. You don't have permission for this operation."
                    }
                }
            
            },
            "post": {
                "tags": ["Users"],
                "description": "This method receive  a json request body  with a username and email and create an account if the account doesn't exists",
                "summary": "Create an user account and returns the user only if user doesn't exists",
                "consumes": "application/json",
                "parameters":{
                    "0": {
                        "name":"user_id",
                        "in": "headers",
                        "description": "ID of the user to turn into an admin",
                        "required": true,
                        "type": "string"
                    }
                },
                "responses": {
                    "201": {
                        "description":"New user created.",
                        "content": {
                            "application/json": {
                                "schema":{
                                        "$ref": "#/components/schemas/User"
                                    },
                                    "examples": {
                                        "users": {
                                            "value": {
                                            "id": "Numero gerado automaticamente",
                                            "name" : "Eduardo",
                                            "admin": "true",
                                            "email": "bls.dudu@gmail.com",
                                            "created_at": "Data formatada",
                                            "updated_at": "Data formatada"
                                            }
                                        }
                                    }
                                }
                            }
                        },                     
                    "400": {
                        "description": "Not possible, user already exists"
                       }
                    }
                }
            },
        "users/{user_id}":{
            "get": {
                "tags": ["Users"],
                "parameters": {
                    "0": {
                        "in": "query",
                        "name":"user_id",
                        "schema": {
                            "type":"string"
                        }                                            }
                },
                "description": "This method returns the user's profile",
                "summary": "return the user's profile",
                "consumes": "application/json",
                "responses": {
                    "200": {
                        "description":"Ok, here are your profile!",
                        "content": {
                            "application/json": {
                                "schema": {     
                                        "$ref": "#/components/schemas/User"
                                    },
                                "examples": {
                                    "users": {
                                        "value": {
                                        "id": "Numero gerado automaticamente",
                                        "name" : "Eduardo",
                                        "admin": "true",
                                        "email": "bls.dudu@gmail.com",
                                        "created_at": "Data formatada",
                                        "updated_at": "Data formatada"
                                        }
                                    }
                                }

                                }
                            }
                        },
                    "404": {
                        "description": "User not found."
                    }
                }
                }
            
            }
            ,
        "users/{user_id}/admin":{
            "get": {
                "tags": ["Users"],
                "parameters": {
                    "0": {
                        "in": "query",
                        "name":"user_id",
                        "schema": {
                            "type":"string"
                        }                                            }
                },
                "description": "This method turns the user in an admin user.",
                "summary": "turn user into an admin user and returns user's profile",
                "consumes": "application/json",
                "responses": {
                    "200": {
                        "description":"Ok, now you are an admin.",
                        "content": {
                            "application/json": {
                                "schema": {     
                                        "$ref": "#/components/schemas/User"
                                    },
                                    "examples": {
                                        "users": {
                                            "value": {
                                            "id": "Numero gerado automaticamente",
                                            "name" : "Eduardo",
                                            "admin": "true",
                                            "email": "bls.dudu@gmail.com",
                                            "created_at": "Data formatada",
                                            "updated_at": "Data formatada"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                    "404": {
                        "description": "User not found."
                    }
                }
                }
            
            }
        },
    "components": {
        "schemas": {
            "User": {
                "type":"object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name" : {
                        "type":"string"
                    },
                    "admin": {
                        "type": "boolean"
                    },
                    "email":{
                        "type":"string"
                    },
                    "created_at": { 
                        "type": "Date"
                    },
                    "updated_at": {
                        "type": "Date"
                    }
                    
                }
               
            },
            "Users": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/User"}
            }
               
        }
           
    }

      
}
    